### ISSUE TITLE
Django 1.10.2 ImportError: cannot import name PassThroughManager

### ISSUE THREAD

**Issue by orggue** [rizumu/django-podcasting#21]
After I installed all the dependencies, add to installed apps this message is shown.
```bash
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/fragmentado/.virtualenvs/papeonerd/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/fragmentado/.virtualenvs/papeonerd/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/home/fragmentado/.virtualenvs/papeonerd/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/fragmentado/.virtualenvs/papeonerd/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/fragmentado/.virtualenvs/papeonerd/local/lib/python2.7/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/fragmentado/.virtualenvs/papeonerd/local/lib/python2.7/site-packages/podcasting/models.py", line 22, in <module>
    from model_utils.managers import PassThroughManager
ImportError: cannot import name PassThroughManager
```

**Comment by rizumu** [comment]
Thanks for the report. I pushed a new version that includes the fix for this. `pip install django-podcasting==1.1`
