### ISSUE TITLE
ValueError at /admin/podcasting/episode/add/

### ISSUE THREAD

**Issue by batisteo** [rizumu/django-podcasting#27]
**"<Episode: Now What?>" needs to have a value for field "id" before this many-to-many relationship can be used.**

```python
Internal Server Error: /admin/podcasting/episode/add/
Traceback (most recent call last):
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/contrib/admin/options.py", line 551, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/contrib/admin/options.py", line 1508, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/contrib/admin/options.py", line 1408, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/contrib/admin/options.py", line 1442, in _changeform_view
    new_object = self.save_form(request, form, change=not add)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/podcasting/admin.py", line 70, in save_form
    return form.save()
  File "/opt/envs/laboren/lib64/python3.5/site-packages/podcasting/forms.py", line 313, in save
    episode.save()
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/base.py", line 806, in save
    force_update=force_update, update_fields=update_fields)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/base.py", line 836, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/base.py", line 922, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/base.py", line 961, in _do_insert
    using=using, raw=raw)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/query.py", line 1060, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1098, in execute_sql
    for sql, params in self.as_sql():
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1051, in as_sql
    for obj in self.query.objs
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1051, in <listcomp>
    for obj in self.query.objs
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1050, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/sql/compiler.py", line 1000, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/fields/files.py", line 297, in pre_save
    file.save(file.name, file.file, save=False)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/fields/files.py", line 94, in save
    name = self.field.generate_filename(self.instance, name)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/fields/files.py", line 328, in generate_filename
    filename = self.upload_to(instance, filename)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/podcasting/models.py", line 92, in get_episode_upload_folder
    if instance.shows.count() == 1:
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 510, in __get__
    return self.related_manager_cls(instance)
  File "/opt/envs/laboren/lib64/python3.5/site-packages/django/db/models/fields/related_descriptors.py", line 827, in __init__
    (instance, self.pk_field_names[self.source_field_name]))
ValueError: "<Episode: Now What?>" needs to have a value for field "id" before this many-to-many relationship can be used.
```

**Comment by batisteo** [comment]
It seems to be caused by `upload_to=get_episode_upload_folder`, where [`instance.shows`](https://github.com/rizumu/django-podcasting/blob/b24976f647faacf4dab2de3a02f8c41017f855ef/podcasting/models.py#L92) is called, when instance is not saved yet, thus have no `pk`/`id`.

In the [Django documentation for `upload_to`](https://docs.djangoproject.com/en/1.11/ref/models/fields/#django.db.models.FileField.upload_to):
> In most cases, this object will not have been saved to the database yet, so if it uses the default **AutoField**, _it might not yet have a value for its primary key field_.

1. Why it worked before?
1. Why using a m2m field for Show-Episode?

**Comment by rizumu** [comment]
Hi @batisteo - I think you are looking for the changes here: https://github.com/rizumu/django-podcasting/issues/15  Sorry for the late reply, please let me know here if that helps or not. Thanks!
